<a href="https://colab.research.google.com/github/alina-bogdanovskaya/PyTorch_Jan2023/blob/lesson1/HW_01.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch

In [2]:
# Создайте случайный FloatTensor размера 3x4x5
a_tensor = torch.randn(size=(3, 4, 5))
a_tensor

tensor([[[-0.6057,  1.4292,  0.4652,  0.4326,  1.1830],
         [-0.8155,  1.3425,  0.9244,  0.8257,  0.9105],
         [-0.3182, -0.1888, -0.2793, -1.4429, -0.4955],
         [ 0.4081,  0.2646,  0.4574, -1.5905,  1.1968]],

        [[ 0.2812,  0.4932, -1.1802, -1.6174,  2.1825],
         [-0.1643, -0.5651, -1.7443, -1.0873, -0.1597],
         [ 1.1220,  0.5330, -1.5163, -0.8565,  0.9490],
         [-0.0584, -0.9013, -0.6493,  0.8205,  0.2689]],

        [[ 1.5146,  0.6689, -2.4208,  0.4443, -1.6283],
         [ 0.9775,  0.0477,  0.3604, -0.2757,  1.9356],
         [-0.0843, -1.7205, -0.9844,  0.0768, -0.1071],
         [ 0.3174, -2.2923, -0.2625,  0.8361,  0.8121]]])

In [3]:
# Выведите его форму (shape)
a_tensor.shape

torch.Size([3, 4, 5])

In [4]:
# Приведите его к форме 6 X 10
b_tensor = a_tensor.reshape(6, 10)
b_tensor

tensor([[-0.6057,  1.4292,  0.4652,  0.4326,  1.1830, -0.8155,  1.3425,  0.9244,
          0.8257,  0.9105],
        [-0.3182, -0.1888, -0.2793, -1.4429, -0.4955,  0.4081,  0.2646,  0.4574,
         -1.5905,  1.1968],
        [ 0.2812,  0.4932, -1.1802, -1.6174,  2.1825, -0.1643, -0.5651, -1.7443,
         -1.0873, -0.1597],
        [ 1.1220,  0.5330, -1.5163, -0.8565,  0.9490, -0.0584, -0.9013, -0.6493,
          0.8205,  0.2689],
        [ 1.5146,  0.6689, -2.4208,  0.4443, -1.6283,  0.9775,  0.0477,  0.3604,
         -0.2757,  1.9356],
        [-0.0843, -1.7205, -0.9844,  0.0768, -0.1071,  0.3174, -2.2923, -0.2625,
          0.8361,  0.8121]])

In [5]:
b_tensor.shape

torch.Size([6, 10])

In [7]:
# Умножьте его на вектор [1, 4, 2, 2, 1] поэлементно
c_vector = torch.IntTensor([1, 4, 2, 2, 1])
a_tensor * c_vector

tensor([[[-0.6057,  5.7167,  0.9303,  0.8651,  1.1830],
         [-0.8155,  5.3699,  1.8488,  1.6514,  0.9105],
         [-0.3182, -0.7552, -0.5587, -2.8857, -0.4955],
         [ 0.4081,  1.0585,  0.9148, -3.1811,  1.1968]],

        [[ 0.2812,  1.9728, -2.3605, -3.2348,  2.1825],
         [-0.1643, -2.2604, -3.4886, -2.1745, -0.1597],
         [ 1.1220,  2.1321, -3.0327, -1.7129,  0.9490],
         [-0.0584, -3.6054, -1.2986,  1.6411,  0.2689]],

        [[ 1.5146,  2.6754, -4.8416,  0.8886, -1.6283],
         [ 0.9775,  0.1906,  0.7209, -0.5515,  1.9356],
         [-0.0843, -6.8821, -1.9687,  0.1536, -0.1071],
         [ 0.3174, -9.1691, -0.5250,  1.6723,  0.8121]]])

In [8]:
# Умножьте тензор матрично на себя, чтобы результат был размерности 6x6
torch.mm(b_tensor, b_tensor.T)


tensor([[ 9.0450, -1.1957, -1.4124, -0.7112, -1.6870, -5.1082],
        [-1.1957,  6.9504,  1.9230, -0.8112,  3.5654, -0.3862],
        [-1.4124,  1.9230, 13.6912,  6.5410, -1.4852,  0.5938],
        [-0.7112, -0.8112,  6.5410,  7.4594,  3.7609,  3.4361],
        [-1.6870,  3.5654, -1.4852,  3.7609, 16.3605,  2.7607],
        [-5.1082, -0.3862,  0.5938,  3.4361,  2.7607, 10.7365]])

In [9]:
# Посчитайте производную функции y = x**3 + z - 75t в точке (1, 0.5, 2)
x = torch.tensor([1.], requires_grad=True)
z = torch.tensor([0.5], requires_grad=True)
t = torch.tensor([2.], requires_grad=True)
y = x**3 + z - 75*t
y.backward()
print(f'Производная по x {x.grad}')
print(f'Производная по z {z.grad}')
print(f'Производная по t {t.grad}')

Производная по x tensor([3.])
Производная по z tensor([1.])
Производная по t tensor([-75.])


In [10]:
# Создайте единичный тензор размера 5x6
d_tensor = torch.eye(5, 6)
d_tensor

tensor([[1., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 1., 0.]])

In [11]:
# Переведите его в формат numpy
d_arr = d_tensor.numpy()
d_arr

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.]], dtype=float32)